# Generated by Django 4.2 on 2023-05-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url', models.URLField(unique=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory', verbose_name='کلاس والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
    ]
