# Generated by Django 4.2.1 on 2023-05-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': ' مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
