# Generated by Django 4.1 on 2023-05-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_remove_comments_title_article_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='بلاگ مربوطه '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(default='hossein@hossein.com', max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='full_name',
            field=models.CharField(default='hossein', max_length=50, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(default='nothing', max_length=500, verbose_name='پیام '),
        ),
    ]
