# Generated by Django 4.1 on 2023-05-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_remove_article_comments_comments_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.comments', verbose_name='کامنت ها '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله مربوطه  '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(default='nothing', max_length=500, verbose_name='پیام '),
        ),
    ]
