# Generated by Django 4.1.2 on 2023-06-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0012_alter_comments_options_alter_comments_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
