# Generated by Django 4.1 on 2023-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0014_alter_article_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ مقاله'),
        ),
    ]
