# Generated by Django 4.1.2 on 2023-06-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0013_remove_article_comment_delete_comments'),
        ('article_module', '0017_alter_article_date'),
    ]

    operations = [
    ]
