# Generated by Django 3.2.20 on 2023-08-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0021_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_Category',
        ),
    ]
