# Generated by Django 4.1 on 2023-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_user_about_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='User-avatar', verbose_name='آواتار'),
        ),
    ]
