# Generated by Django 4.1 on 2023-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0017_remove_teachers_expertise'),
        ('user_module', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='talen',
            field=models.ManyToManyField(to='teacher_module.talentcategory', verbose_name='مهارت'),
        ),
    ]
