# Generated by Django 4.1 on 2023-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0017_remove_teachers_expertise'),
        ('user_module', '0007_user_talen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='talen',
        ),
        migrations.AddField(
            model_name='user',
            name='talent',
            field=models.ManyToManyField(to='teacher_module.talentcategory', verbose_name='مهارت یا دسته بندی مورد علاقه '),
        ),
    ]
