# Generated by Django 4.1.2 on 2023-06-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_user_number'),
        ('user_module', '0008_remove_user_talen_user_talent'),
    ]

    operations = [
    ]
