# Generated by Django 4.1.2 on 2023-06-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_sliders_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='گالری اسلایدر')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slidergallery', to='site_module.sliders')),
            ],
        ),
    ]
