# Generated by Django 4.1 on 2023-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0003_alter_teachers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, verbose_name='  نام و نام خانوادگی مدرس'), max_length=200, unique=True, verbose_name='عنوان در URL'),
        ),
    ]
