# Generated by Django 4.1 on 2023-06-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0005_alter_teachers_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مهارت ها ',
                'verbose_name_plural': 'دسته بندی های مهارت ها ',
            },
        ),
        migrations.AddField(
            model_name='teachers',
            name='talent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher_module.talentcategory', verbose_name='مهارت استاد '),
        ),
    ]
