# Generated by Django 4.1 on 2023-06-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0006_talentcategory_teachers_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='talent',
        ),
    ]
