# Generated by Django 4.1 on 2023-06-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0007_remove_teachers_talent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentcategory',
            options={'verbose_name': 'دسته بندی مهارتها', 'verbose_name_plural': 'دسته بندی های مهارتها'},
        ),
    ]
