# Generated by Django 4.1 on 2023-06-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0009_alter_teachers_numberofcorses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TalentCategory',
        ),
    ]
