# Generated by Django 4.1 on 2023-06-04 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0011_talentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentcategory',
            name='url',
            field=models.CharField(default=True, max_length=200, unique=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='talent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_module.talentcategory', verbose_name='مهارت استاد '),
        ),
    ]
