# Generated by Django 4.1 on 2023-06-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0012_talentcategory_url_teachers_talent'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_module.talentcategory', verbose_name='کلاس والد'),
        ),
    ]
