# Generated by Django 4.1 on 2023-06-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0013_talentcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='talent',
        ),
        migrations.AddField(
            model_name='teachers',
            name='talent',
            field=models.ManyToManyField(default=True, to='teacher_module.talentcategory', verbose_name='مهارت استاد '),
        ),
    ]
