# Generated by Django 4.1 on 2023-06-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0015_alter_teachers_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='talent',
        ),
        migrations.AddField(
            model_name='teachers',
            name='talent',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_module.talentcategory', verbose_name='مهارت استاد '),
        ),
    ]
