# Generated by Django 4.1 on 2023-06-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_module', '0016_remove_teachers_talent_teachers_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='Expertise',
        ),
    ]
