# Generated by Django 4.2 on 2023-05-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_articlecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='url',
            field=models.CharField(max_length=200, unique=True, verbose_name='لینک'),
        ),
    ]
