# Generated by Django 4.2 on 2023-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_alter_articlecategory_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='عنوان در URL')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(upload_to='article-images')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('selected_categories', models.ManyToManyField(to='article_module.articlecategory', verbose_name='دسته بندی ها ')),
            ],
        ),
    ]
