# Generated by Django 4.1 on 2023-05-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('message', models.CharField(max_length=500, verbose_name='پیام ')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.articlecategory')),
            ],
        ),
    ]
