# Generated by Django 4.1 on 2023-05-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
