# Generated by Django 4.2 on 2023-05-10 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 5, 10), verbose_name='زمان انتشار'),
            preserve_default=False,
        ),
    ]
