# Generated by Django 4.1 on 2023-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0008_comments_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(to='article_module.comments', verbose_name='کامنت ها '),
        ),
    ]
