# Generated by Django 4.2 on 2023-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_article_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
    ]
