# Generated by Django 4.2 on 2023-05-13 05:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_articlecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان انتشار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='text',
            field=models.TextField(default=datetime.datetime(2023, 5, 13, 5, 50, 8, 765577, tzinfo=datetime.timezone.utc), verbose_name='متن'),
            preserve_default=False,
        ),
    ]
