# Generated by Django 4.1.2 on 2023-05-13 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_module', '0012_articlecomments_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleComments',
            new_name='Comments',
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': ' کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_created',
        ),
    ]
