# Generated by Django 4.1.2 on 2023-05-13 16:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article_module', '0013_rename_articlecomments_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 5, 13, 19, 35, 14, 266348), verbose_name='زمان انتشار'),
            preserve_default=False,
        ),
    ]
